### DISCUSSION TITLE
db adapter and the db_profile setup

### DISCUSSION THREAD

**Discussion by arybach** [fal-ai/dbt-fal#707] [Q&A] [answered]
Hihi,

"fal credentials must have a `db_profile` property set"
Can you please clarify somewhere in docs how to setup db adapter and the db_profile for fal properly?
I couldn't find any info on that.

before fal & dbt-fall installation 

dbt --version returns
Core:
  - installed: 1.3.1
  - latest:    1.3.1 - Up to date!

Plugins:
  - postgres: 1.3.1 - Up to date!

after:
Encountered an error:
fal credentials must have a `db_profile` property set

Thx vm.

alex

**Comment by mederka** [comment, marked as answer]
Hi @arybach, thanks for raising this! We will definitely clarify it in our docs. In the meantime have you looked through the [quickstart guide](https://docs.fal.ai/dbt-fal/quickstart) to dbt-fal? And if so, I would be curious if you updated your `profiles.yml` the way it's suggested in our guide.

**Reply by arybach** [reply]
Quickstart only has an extraction example of the profiles.yml (https://docs.fal.ai/fal/credentials-profile)
i'd prefer something more basic initially
adding... 

fal_test:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 4

doesn't change anything. 
that's why i'm asking for more step-by-step details on how to modify settings incrementally.
Thank you very much.

**Reply by mederka** [reply]
I see. Sorry for the confusion, I'll open a PR addressing this later today. In order to use dbt-fal, you need to define another output like this:
```
fal_test:
  target: dev_fal
  outputs:
    dev_fal:
      type: fal
      db_profiles: dev
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
```
