### DISCUSSION TITLE
dbt-fal flow run -s ./models/t.sql force refer source.json and run_result.json

### DISCUSSION THREAD

**Discussion by Mrzyxing** [fal-ai/dbt-fal#917] [Q&A]
As title metioned, I got an error when run `dbt-fal flow run -s "+./models/t1.sql"` with my test project.
`dbt_peoject.yml`
```
name: 'ubt_etl'
version: '1.0.0'
config-version: 2
profile: "t1"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

```
`./models/schema.yml`
```
models:
  - name: t1
    description: Ozone levels
    config:
      materialized: table
    meta:
      fal:
        pre-hook:
          - ./fal_scripts/pre-check.py
        post-hook:
          - ./fal_scripts/hook.py
  - name: t
    meta:
      fal:
        pre-hook:
          - ./fal_scripts/pre-check.py
        post-hook:
          - ./fal_scripts/hook.py
```
![image](https://github.com/fal-ai/dbt-fal/assets/15867085/ddeaf5ab-ae6a-47e7-8e87-4cd323e7fdb0)
And it looks will fail if missing `sources.json` under target directory.
Is here any solution can disable force reference on `sources.json` and `run_result.json` ? Or just I run with wrong command/configuration ? (also a beginner of DBT :-) )
Run `dbt-fal flow run` got correct result.
